/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Apps {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Apps().getGreeting());
    }
}